doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        default_entity_manager: default
        enable_native_lazy_objects: true

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false

                mappings:
                    Task:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Task/Infrastructure/Persistence/Doctrine/Entity'
                        prefix: 'App\Task\Infrastructure\Persistence\Doctrine\Entity'
                        alias: Task
