doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        default_entity_manager: default
        enable_native_lazy_objects: true

        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: false

                mappings:
                    Animation:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Animation/Infrastructure/Persistence/Doctrine/Entity'
                        prefix: 'App\Animation\Infrastructure\Persistence\Doctrine\Entity'
                        alias: Animation

                    Composition:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Composition/Infrastructure/Persistence/Doctrine/Entity'
                        prefix: 'App\Composition\Infrastructure\Persistence\Doctrine\Entity'
                        alias: Composition
